### PR TITLE
Keyboard and preferences

### LINKED ISSUE #146: As a user, I should be able to navigate a book using the keyboard
And not by tabbing to controls.

- [ ] left/right arrow should de/advance through `flow`
- [ ] page up / page down should advanced through `scrolled-doc`

### PR DESCRIPTION
**Pull request by respinos**
- supports keyboard navigation using arrows and page up/down/home/end
- changes the behavior of the next/previous navigation buttons in `scrolled-doc` to scroll the display instead of navigating to another chapter (matching `flow` behavior)
- preferences widget has been refactored to improve future extensibility
- preferences are saved to `localStorage` so persist on reloads

Closes #146

### CODE REVIEW

**Comment by respinos** [comment]
@jmcglone - maybe this closes #99 ?

**Comment by jmcglone** [comment]
Looks great! I tested this branch locally. A note: 

1) What about the width of the text re-sizer in the preferences? It is a little too wide/flowing out of the modal. 

screen shot 2018-04-19 at 11 29 54 am

What's breaking here -- should the width of the modal expand with the width of `.preview--text_size`? Or should we set the width of `.preview--text_size` to `auto`? It cuts off the preview box a bit when the text size is large...but I _think_ that's okay.

screen shot 2018-04-19 at 12 32 12 pm

**Comment by respinos** [comment]
I knew I was forgetting something: I tried to size the preview with `rem` which wasn't as reliable as I'd hoped across browsers. We should set a fixed width/height for the preview.

In your second screenshot --- mm. Yeah, I may have taken clipping overflow to the extreme (Readium wraps the text; I'll take a look.)

**Comment by respinos** [comment]
Gave the preview a `%` width, which keeps it from blowing out the panel.

**Pull request merged**
