### PR TITLE
Scrolled doc and highlighting

### LINKED ISSUE #63: Scroll mode does not scroll
As a reader, when I select the "Scroll" reading/display mode in the EPUB Reader, I cannot scroll the page.

### LINKED ISSUE #68: Internal links don't work
Internal links to other pages/parts of the EPUB such as chapters or footnotes do not seem to be working in any EPUB using the epub js v.3 engine - a good test EPUB is the "internal links" example.

### PR DESCRIPTION
**Pull request by respinos**
- update epub.js v0.3 with latest from futurepress + patches
- export `annotations` object for epub.js v0.3
  - normalize hrefs from contents vs. spine
  - adjust calculation of scrolled-doc iframe height
- re-arrange re-opening of epub when preferences are used to change between flow vs. scrolled-doc
- attach events to respond to internal links

Fixes #68 
Fixes #63

### CODE REVIEW

**Comment by jmcglone** [comment]
@respinos in scroll mode, when I click to advance to the next section, the next section never loads and I get the following error:

screen shot 2017-09-05 at 11 35 15 am

**Comment by respinos** [comment]
Swell. Looking into why the rendition would be so different in this mode.

**Comment by respinos** [comment]
@jmcglone - refactored `reopen` again; more red herrings caught.

**Comment by respinos** [comment]
@jmcglone - updated epub.js to fix bug where the stage wouldn't set `overflow` when toggling between `flow` options.

**Comment by sethaj** [comment]
When I'm the first page of "Moby Dick" the "next" button doesn't seem to do anything. This is in either scroll or page mode. If I manually choose a different chapter, then the next/previous buttons are find (in either scroll or page mode).

**http://127.0.0.1:8080/cozy-sun-bear/examples/example.html?/epub3-samples/30/moby-dick/**

**Comment by respinos** [comment]
We should file that as an issue, and move on.

**Pull request merged**
